### ISSUE TITLE
报错UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 146793: invalid start byte

### ISSUE THREAD

**Issue by shuishiba1997** [luzhixing12345/xiaohongshu-spider#3]
直接进行解析
Traceback (most recent call last):
  File "main.py", line 91, in <module>
    main(args)
  File "main.py", line 31, in main
    articles = getXHScontent(word)
  File "C:\Users\ADMIN\Desktop\xiaohongshu-spider-master\selenium_process.py", line 55, in getXHScontent
    URL = urlProcess(word)
  File "C:\Users\ADMIN\Desktop\xiaohongshu-spider-master\selenium_process.py", line 24, in urlProcess
    file_data = file.read()
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python37\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 146793: invalid start byte

**Comment by shuishiba1997** [comment]
请教一下这个该如何处理？

**Comment by shuishiba1997** [comment]
已解决，谢谢

**Comment by luzhixing12345** [comment]
额好，解决了就行
